### ISSUE TITLE
geometry nodes

### ISSUE THREAD

**Issue by ekswathi** [ozikazina/Hydra#3] opened 2024-01-17 06:01 UTC
Hi bro, nice to see you are updating this amazing addon. Just a suggestion. can we convert this addon to a node based one?

**Comment by ozikazina** [comment] 2024-01-17 07:58
Hello, I already have an implementation I'd like to push. It uses a custom Geometry Nodes group, which displaces the surface. It can be applied on it's own or automatically inserted into the last Nodes group in the modifier stack. It would also replace the displace modifier as a preview for erosion.
The issue is that each object needs a unique scale for the displacement, which makes it harder to use elsewhere by hand. If you have any suggestions, let me know.
I wanted to update it alongside a new erosion algorithm, but I'll see how well it goes today.

**Comment by ekswathi** [comment] 2024-01-17 14:22
hydra is really fast. I tried it with A.N.T landscape addon and manually sculpted models both working nice(i mean depending up on the topology of sculpted mesh)
Thank you

**Comment by abhiraaid** [comment] 2024-02-28 09:35
Hello, great add-on here. Thanks 

> Hello, I already have an implementation I'd like to push. It uses a custom Geometry Nodes group, which displaces the surface. It can be applied on it's own or automatically inserted into the last Nodes group in the modifier stack. It would also replace the displace modifier as a preview for erosion. The issue is that each object needs a unique scale for the displacement, which makes it harder to use elsewhere by hand. If you have any suggestions, let me know. I wanted to update it alongside a new erosion algorithm, but I'll see how well it goes today.

regarding the scale you can capture the Max Z height using a Bounding Box node on the terrain, then map range the displacement scale using that.

**Comment by ozikazina** [comment] 2024-05-06 10:05
Hello, sorry for not responding for so long. I've been swamped with schoolwork.

I've redesigned the heightmaps so that every modifier can have a scale of 1. I've also added a different erosion algorithm. All changes are now in the mei branch. It'll be a few more weeks before I can fully test and release it. Thank you for the suggestions!

**Comment by ekswathi** [comment] 2024-06-16 05:23
any news bro?

**Comment by ozikazina** [comment] 2024-06-16 07:32
If I don't discover any major bugs then it should be out today. I added a different algorithm for water erosion and setting up its parameters turned out to be a nightmare. I spent the last two weeks staring at pixels.

**Comment by ozikazina** [comment] 2024-06-16 18:45
I have just released the latest version. I'll update the GitHub readme tomorrow alongside a tutorial for the new features. As this issue was initially about geometry nodes I'll close it afterwards if no new bugs pop up.

**Comment by ekswathi** [comment] 2024-06-17 04:52
really nice. just playing with it.

**Closed** 2024-06-19 14:03 UTC
